theme: minima
title: pequode
description: Platform engineering, scientific computing, and applied ML.
author:
  name: pequode

github_username: pequode

header_pages:
  - about.md

collections:
  projects:
    output: true
    sort_by: order

url: https://pequode.github.io/

include:
  - assets/scripts/pkg